# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local zacchaeusayanniran/udagram-frontend:v1 #tagging
    - run: docker tag udagram-api-user zacchaeusayanniran/udagram-api-user:v1
    - run: docker tag udagram-api-feed zacchaeusayanniran/udagram-api-feed:v1
    - run: docker tag udagram-reverseproxy zacchaeusayanniran/udagram-reverseproxy:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push zacchaeusayanniran/udagram-frontend:v1
    - run: docker push zacchaeusayanniran/udagram-api-user:v1
    - run: docker push zacchaeusayanniran/udagram-api-feed:v1
    - run: docker push zacchaeusayanniran/udagram-reverseproxy:v1
  
